### ISSUE TITLE
Specify install() parameter

### ISSUE THREAD

**Issue by biafra23** [bertrandmartel/javacard-gradle-plugin#4]
Is it possible to specify an install APDU that is passed to install() on the Applet? 
Like `--params` in gp.

If it is not possible ATM would you consider accepting a PR implementing this?

**Comment by martinpaljak** [comment]
I understand you can give arguments to GpExec which would include --params ?

**Comment by bertrandmartel** [comment]
Yes like @martinpaljak suggested you can invoke Global Plaform pro by creating a `GpExec` task. 

To reproduce the default install task, it would be something like : 

```groovy
import fr.bmartel.javacard.util.Utility

def gpargs = [
        '-relax',
        '--delete',
        Utility.formatByteArray('A0:00:00:01:51:41:43:4C:00'),
        '--install',
        new File(project.buildDir.absolutePath + File.separator + "javacard" + File.separator + 'applet.cap').absolutePath
]

task customInstall(type: fr.bmartel.javacard.gp.GpExec) {
    description = 'custom Global Platform pro install'
    group = 'build'
    args gpargs
    doFirst {
        println('gp ' + args)
    }
}
```

To run with : 

```bash
./gradlew customInstall
```
[here](https://github.com/bertrandmartel/javacard-gradle-plugin/blob/e9fd054e1e104bacfc2ebe6cde1b66b914d372bd/gradle-javacard/src/main/groovy/fr/bmartel/javacard/JavaCardPlugin.groovy#L271-L292) is where the install tasks is created with given parameters (with additionnal key arguments)

For the example above, the arguments will be : 

```
gp [-relax, --delete, A00000015141434C00, --install, /home/user/applet/app/build/javacard/applet.cap]
```

**Comment by martinpaljak** [comment]
I have to check, but you should not be forced to format the argument to --delete and should be able to use the XX:XX format. If not, it is a bug :)

**Comment by bertrandmartel** [comment]
@martinpaljak thanks I've just checked it's working in the most recent version but not in the current one I'm using. My GPro version date back to 09/2017 so I will need to update #5

**Comment by biafra23** [comment]
The custom task seems to work. I will go with that for now. 
Thanks!
