### ISSUE TITLE
Update Global Platform Pro

### ISSUE THREAD

**Issue by bertrandmartel** [bertrandmartel/javacard-gradle-plugin#5]
Update to v0.3.10rc7 : 

* update source directory
* remove conversion of XX:XX format for applet ID

**Comment by martinpaljak** [comment]
Maybe wait a bit until the rc is removed? I have intentionally not updated the Maven version.

**Comment by bertrandmartel** [comment]
@martinpaljak Ok let's do that :+1:

**Comment by bertrandmartel** [comment]
I've updated the library to be able to use global platform pro from dependencies eg :

```gradle
apply plugin: 'javacard'

dependencies {
    compile 'com.github.martinpaljak:globalplatformpro:18.09.14'
}

javacard {
.....
}
```
So in the future version can be upgraded manually by user
