### ISSUE TITLE
GPTool task ClassNotFoundException: com.payneteasy.tlv.BerTlvParser error

### ISSUE THREAD

**Issue by CCob** [bertrandmartel/javacard-gradle-plugin#6]
Hi,

I have started working with this gradle plugin and I must say, it's great.  Compiling CAP files within IntelliJ is a breeze.

One issue I have come across though with 1.6.1 which I see both yourself and ph4r05 work on together is that GPTool task do run run with the following error

```
Exception in thread "main" java.lang.NoClassDefFoundError: com/payneteasy/tlv/BerTlvParser
	at pro.javacard.gp.GlobalPlatform.discover(GlobalPlatform.java:148)
	at pro.javacard.gp.GPTool.main(GPTool.java:373)
Caused by: java.lang.ClassNotFoundException: com.payneteasy.tlv.BerTlvParser
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
```

After checking the gradle-javacard-1.6.1.jar file I do see that indeed the class is missing.  Checking a local build of GPTool myself and the BerTlvParser classes are bundles inside GPTool.

Thanks
CCob

**Comment by CCob** [comment]
FYI, adding ber-tlv package to the dependencies section works

```compile 'com.payneteasy:ber-tlv:1.0-8'```

**Comment by bertrandmartel** [comment]
Hello thanks for your feedback, I think you refer to @ph4r05 fork [here](https://github.com/ph4r05/javacard-gradle-plugin) which is based on a forked version of global-platform-pro which is more recent and have the new `com.payneteasy:ber-tlv:1.0-8` dependency. I've not updated yet the global platform pro dependency, see #5

**Comment by CCob** [comment]
Yes, that's correct.  I think all that needs to happen is for a fat jar to be create with the dependency in tow or `com.payneteasy:ber-tlv` needs to be included as a runtime dependency.

**Comment by bertrandmartel** [comment]
In fact these dependencies are automatically resolved by the plugin [here](https://github.com/bertrandmartel/javacard-gradle-plugin/blob/master/gradle-javacard/src/main/groovy/fr/bmartel/javacard/JavaCardPlugin.groovy#L60-L69) but the list needs to be updated if the recent version of global platform pro is used

**Comment by bertrandmartel** [comment]
You can now choose the version of global platform pro from 1.5.6 with :

```gradle
apply plugin: 'javacard'

dependencies {
    compile 'com.github.martinpaljak:globalplatformpro:18.09.14'
}

javacard {
....
}
```
