### ISSUE TITLE
Error: "attempt to instantiate an abstract class"

### ISSUE THREAD

**Issue by johnnytshi** [bertrandmartel/javacard-gradle-plugin#7]
My card has some special api baked in, to access them, the vendor provided me with a jar and a exp (the jar file consists of a few java files, which has empty implementation, sort like a header file).

I have added both to my depencies, like so:

local {
    jar rootPath + '/sdk/special.jar'
    exps rootPath + '/sdk'
}

but now I am getting an error `[ant:convert] NEW: attempt to instantiate an abstract class`

any idea?

all the best

**Comment by martinpaljak** [comment]
This is probably from your applet source code than the build system?

**Comment by johnnytshi** [comment]
I understand that.

If I setup the project using NetBean, I am supposed to import the jar and select "already on card".  So the compiler ONLY links against the jar.

How can I accomplish the same thing with the gradle plugin? is that even possible?

**Comment by martinpaljak** [comment]
This is an error from the offcard verifier, meaning that the applet code you have is not correct.

**Comment by johnnytshi** [comment]
yup, it's the exp file. Tried an older file, and it worked

thanks!
